services:
  db:
    image: postgres:16
    container_name: anomaly_db
    environment:
      POSTGRES_USER: anomaly
      POSTGRES_PASSWORD: anomaly_dev
      POSTGRES_DB: anomaly_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U anomaly -d anomaly_db"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
