/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Datasets */
        get: operations["list_datasets_upload_get"];
        put?: never;
        /** Upload Csv */
        post: operations["upload_csv_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/upload/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Upload */
        post: operations["analyze_upload_upload_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/upload/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Commit Upload */
        post: operations["commit_upload_upload_commit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/train/{dataset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Train */
        post: operations["train_train__dataset_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/train/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Models */
        get: operations["list_models_train_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/predict/{model_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Predict */
        post: operations["predict_predict__model_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/predict/{model_id}/batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Labeled Batches
         * @description Every Predict run against this model that included a usable ground-truth
         *     label -- ordinary unlabeled predictions never show up here.
         */
        get: operations["list_labeled_batches_predict__model_id__batches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/predict/{model_id}/batches/{batch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Labeled Batch */
        get: operations["get_labeled_batch_predict__model_id__batches__batch_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/anomalies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Anomalies */
        get: operations["list_anomalies_anomalies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/anomalies/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Label Anomaly */
        patch: operations["label_anomaly_anomalies__event_id__patch"];
        trace?: never;
    };
    "/settings/threshold/{model_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Threshold */
        get: operations["get_threshold_settings_threshold__model_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Threshold */
        patch: operations["update_threshold_settings_threshold__model_id__patch"];
        trace?: never;
    };
    "/subjects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Subjects */
        get: operations["list_subjects_subjects_get"];
        put?: never;
        /** Create Subject */
        post: operations["create_subject_subjects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subjects/{subject_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Subject */
        get: operations["get_subject_subjects__subject_id__get"];
        put?: never;
        post?: never;
        /** Delete Subject */
        delete: operations["delete_subject_subjects__subject_id__delete"];
        options?: never;
        head?: never;
        /** Update Subject */
        patch: operations["update_subject_subjects__subject_id__patch"];
        trace?: never;
    };
    "/subjects/{subject_id}/retrain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retrain Subject */
        post: operations["retrain_subject_subjects__subject_id__retrain_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subjects/{subject_id}/threshold-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Threshold History */
        get: operations["list_threshold_history_subjects__subject_id__threshold_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subjects/{subject_id}/data-review/precheck": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Precheck Data Review
         * @description Runs (or reuses) the candidate-anomaly scan on the newest dataset.
         */
        post: operations["precheck_data_review_subjects__subject_id__data_review_precheck_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subjects/{subject_id}/data-review/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Data Review Candidates */
        get: operations["list_data_review_candidates_subjects__subject_id__data_review_candidates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subjects/{subject_id}/data-review/candidates/{candidate_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Label Data Review Candidate */
        patch: operations["label_data_review_candidate_subjects__subject_id__data_review_candidates__candidate_id__patch"];
        trace?: never;
    };
    "/subjects/{subject_id}/train-alternative": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Train Alternative */
        post: operations["train_alternative_subjects__subject_id__train_alternative_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subjects/{subject_id}/models/{model_id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate Model */
        post: operations["activate_model_subjects__subject_id__models__model_id__activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/experiments/personalization": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Personalization */
        post: operations["personalization_experiments_personalization_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/experiments/preset-demo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preset Demo */
        post: operations["preset_demo_experiments_preset_demo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/experiments/evaluation-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Evaluation Summary
         * @description Cross-Subject F1/precision/recall/AUC summary -- additive to (never
         *     a substitute for) each Subject's own number. Silently includes only
         *     Subjects that have both an active model and a labeled evaluation;
         *     everyone else is reported in excluded_subject_ids rather than causing
         *     an error, since most Subjects won't have a label column.
         */
        get: operations["evaluation_summary_experiments_evaluation_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnomalyOut */
        AnomalyOut: {
            /** Id */
            id: number;
            /** Prediction Id */
            prediction_id: number;
            /** Model Id */
            model_id: number;
            /** Subject Id */
            subject_id: number;
            /** Window Idx */
            window_idx: number;
            /** Score */
            score: number;
            /** Severity */
            severity: string;
            /** Label */
            label: string;
            /** Note */
            note?: string | null;
            /** Created At */
            created_at: string;
            /** Outcome */
            outcome?: string | null;
            /**
             * Detection Source
             * @default flagged
             */
            detection_source: string;
        };
        /** Body_analyze_upload_upload_analyze_post */
        Body_analyze_upload_upload_analyze_post: {
            /** File */
            file: string;
        };
        /** Body_predict_predict__model_id__post */
        Body_predict_predict__model_id__post: {
            /** File */
            file: string;
        };
        /** Body_upload_csv_upload_post */
        Body_upload_csv_upload_post: {
            /** File */
            file: string;
        };
        /** CommitIn */
        CommitIn: {
            /** Temp Id */
            temp_id: string;
            /** Target */
            target: string;
            /** Subject Name */
            subject_name?: string | null;
            /** Subject Description */
            subject_description?: string | null;
            /** Subject Id */
            subject_id?: number | null;
            split: components["schemas"]["SplitConfig"];
            /** Algorithm */
            algorithm?: string | null;
            /** Label Column */
            label_column?: string | null;
        };
        /** ConfusionOut */
        ConfusionOut: {
            /** Tp */
            tp: number;
            /** Fp */
            fp: number;
            /** Tn */
            tn: number;
            /** Fn */
            fn: number;
        };
        /** CrossApplicationOut */
        CrossApplicationOut: {
            /** Global Epsilon */
            global_epsilon: number;
            /** Fp Rate At Global */
            fp_rate_at_global: {
                [key: string]: number | null;
            };
            /** Miss Rate At Global */
            miss_rate_at_global: {
                [key: string]: number | null;
            };
        };
        /** CurvePointOut */
        CurvePointOut: {
            /** I */
            i: number;
            /** Score */
            score: number;
            /** Actual */
            actual: number;
            /** Predicted */
            predicted: number;
        };
        /** DataReviewCandidateOut */
        DataReviewCandidateOut: {
            /** Id */
            id: number;
            /** Dataset Id */
            dataset_id: number;
            /** Row Index */
            row_index: number;
            /** Score */
            score: number;
            /** Row Preview */
            row_preview: {
                [key: string]: unknown;
            };
            /** Label */
            label: string;
            /** Created At */
            created_at: string;
        };
        /** DataReviewLabelIn */
        DataReviewLabelIn: {
            /** Label */
            label: string;
        };
        /** DatasetOut */
        DatasetOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** N Rows */
            n_rows: number | null;
            /** N Features */
            n_features: number | null;
            /** Uploaded At */
            uploaded_at: string;
        };
        /** EvaluationOut */
        EvaluationOut: {
            /** Precision */
            precision: number;
            /** Recall */
            recall: number;
            /** F1 */
            f1: number;
            /** Auc */
            auc: number | null;
            /** N Test Samples */
            n_test_samples?: number | null;
            /** N Test Positive */
            n_test_positive?: number | null;
            /** Epsilon */
            epsilon?: number | null;
            confusion?: components["schemas"]["ConfusionOut"] | null;
            /** Curve */
            curve?: components["schemas"]["CurvePointOut"][] | null;
        };
        /** EvaluationSummaryOut */
        EvaluationSummaryOut: {
            /** Subject Ids */
            subject_ids: number[];
            /** Excluded Subject Ids */
            excluded_subject_ids: number[];
            /** N Labeled Subjects */
            n_labeled_subjects: number;
            /** N Unlabeled Subjects */
            n_unlabeled_subjects: number;
            /** F1 By Subject */
            f1_by_subject: {
                [key: string]: number;
            };
            f1_statistics: components["schemas"]["StatisticsOut"] | null;
            precision_statistics: components["schemas"]["StatisticsOut"] | null;
            recall_statistics: components["schemas"]["StatisticsOut"] | null;
            auc_statistics: components["schemas"]["StatisticsOut"] | null;
        };
        /** ExperimentOut */
        ExperimentOut: {
            /** Subject Ids */
            subject_ids: number[];
            /** Epsilons */
            epsilons: {
                [key: string]: number;
            };
            statistics: components["schemas"]["StatisticsOut"];
            cross_application: components["schemas"]["CrossApplicationOut"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LabelIn */
        LabelIn: {
            /** Label */
            label: string;
            /** Note */
            note?: string | null;
        };
        /** LoginIn */
        LoginIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** ModelOut */
        ModelOut: {
            /** Id */
            id: number;
            /** Algorithm */
            algorithm: string;
            /** Selection Reason */
            selection_reason: string | null;
            /** Selection Mode */
            selection_mode: string;
            /** Status */
            status: string;
            /** Is Active */
            is_active: boolean;
            /** Trained At */
            trained_at: string | null;
            threshold: components["schemas"]["app__api__subjects__ThresholdOut"] | null;
            evaluation?: components["schemas"]["EvaluationOut"] | null;
        };
        /** PersonalizationIn */
        PersonalizationIn: {
            /** Subject Ids */
            subject_ids: number[];
        };
        /** PredictBatchDetailOut */
        PredictBatchDetailOut: {
            /** Batch Id */
            batch_id: string;
            /** Model Id */
            model_id: number;
            /** Created At */
            created_at: string;
            /** N Windows */
            n_windows: number;
            confusion: components["schemas"]["PredictConfusionOut"];
            /** Curve */
            curve: components["schemas"]["PredictCurvePointOut"][];
        };
        /** PredictBatchSummaryOut */
        PredictBatchSummaryOut: {
            /** Batch Id */
            batch_id: string;
            /** Model Id */
            model_id: number;
            /** Created At */
            created_at: string;
            /** N Windows */
            n_windows: number;
            confusion: components["schemas"]["PredictConfusionOut"];
        };
        /** PredictConfusionOut */
        PredictConfusionOut: {
            /** Tp */
            tp: number;
            /** Fp */
            fp: number;
            /** Tn */
            tn: number;
            /** Fn */
            fn: number;
        };
        /** PredictCurvePointOut */
        PredictCurvePointOut: {
            /** I */
            i: number;
            /** Score */
            score: number;
            /** Actual */
            actual: number;
            /** Predicted */
            predicted: number;
        };
        /** PresetDemoOut */
        PresetDemoOut: {
            /** Subject Ids */
            subject_ids: number[];
            /** Epsilons */
            epsilons: {
                [key: string]: number;
            };
            statistics: components["schemas"]["StatisticsOut"];
            cross_application: components["schemas"]["CrossApplicationOut"];
            /** Created Subject Ids */
            created_subject_ids: number[];
        };
        /** RecalibrateIn */
        RecalibrateIn: {
            /** Z Multiplier */
            z_multiplier: number;
        };
        /** RegisterIn */
        RegisterIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** RetrainOut */
        RetrainOut: {
            /** Model Id */
            model_id: number;
            /** Old Epsilon */
            old_epsilon: number | null;
            /** New Epsilon */
            new_epsilon: number;
            /** Delta Pct */
            delta_pct: number | null;
        };
        /** SplitConfig */
        SplitConfig: {
            /** Mode */
            mode: string;
            /** Column */
            column?: string | null;
            /** Period */
            period?: string | null;
        };
        /** StatisticsOut */
        StatisticsOut: {
            /** Mean */
            mean: number;
            /** Std */
            std: number;
            /** Min */
            min: number;
            /** Max */
            max: number;
            /** Range Ratio */
            range_ratio: number | null;
        };
        /** SubjectCreate */
        SubjectCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
        };
        /** SubjectDetailOut */
        SubjectDetailOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Source Hint */
            source_hint: string | null;
            /** Is Default */
            is_default: boolean;
            /** Created At */
            created_at: string;
            /** N Datasets */
            n_datasets: number;
            /** N Models */
            n_models: number;
            /** N Anomalies */
            n_anomalies: number;
            /** Active Epsilon */
            active_epsilon: number | null;
            /** Active Algorithm */
            active_algorithm: string | null;
            /** Active Model Id */
            active_model_id: number | null;
            /** Active Mu */
            active_mu: number | null;
            /** Active Sigma */
            active_sigma: number | null;
            /** Active Z Multiplier */
            active_z_multiplier: number | null;
            /** Active F1 */
            active_f1?: number | null;
            /** Active Auc */
            active_auc?: number | null;
            /**
             * Pre Retrain Check Enabled
             * @default false
             */
            pre_retrain_check_enabled: boolean;
            /** Datasets */
            datasets: components["schemas"]["DatasetOut"][];
            /** Models */
            models: components["schemas"]["ModelOut"][];
        };
        /** SubjectOut */
        SubjectOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Source Hint */
            source_hint: string | null;
            /** Is Default */
            is_default: boolean;
            /** Created At */
            created_at: string;
            /** N Datasets */
            n_datasets: number;
            /** N Models */
            n_models: number;
            /** N Anomalies */
            n_anomalies: number;
            /** Active Epsilon */
            active_epsilon: number | null;
            /** Active Algorithm */
            active_algorithm: string | null;
            /** Active Model Id */
            active_model_id: number | null;
            /** Active Mu */
            active_mu: number | null;
            /** Active Sigma */
            active_sigma: number | null;
            /** Active Z Multiplier */
            active_z_multiplier: number | null;
            /** Active F1 */
            active_f1?: number | null;
            /** Active Auc */
            active_auc?: number | null;
            /**
             * Pre Retrain Check Enabled
             * @default false
             */
            pre_retrain_check_enabled: boolean;
        };
        /** SubjectUpdate */
        SubjectUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Pre Retrain Check Enabled */
            pre_retrain_check_enabled?: boolean | null;
        };
        /** ThresholdHistoryOut */
        ThresholdHistoryOut: {
            /** Id */
            id: number;
            /** Model Id */
            model_id: number;
            /** Algorithm */
            algorithm: string;
            /** Mu */
            mu: number;
            /** Sigma */
            sigma: number;
            /** Epsilon */
            epsilon: number;
            /** Z Multiplier */
            z_multiplier: number;
            /** N Rows */
            n_rows: number | null;
            /** Source */
            source: string;
            /** Created At */
            created_at: string;
        };
        /** TokenOut */
        TokenOut: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** TrainAlternativeIn */
        TrainAlternativeIn: {
            /** Algorithm */
            algorithm: string;
        };
        /** TrainAlternativeOut */
        TrainAlternativeOut: {
            /** Model Id */
            model_id: number;
            /** Algorithm */
            algorithm: string;
            /** Epsilon */
            epsilon: number;
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: number;
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** ThresholdOut */
        app__api__settings__ThresholdOut: {
            /** Model Id */
            model_id: number;
            /** Mu */
            mu: number;
            /** Sigma */
            sigma: number;
            /** Epsilon */
            epsilon: number;
            /** Z Multiplier */
            z_multiplier: number;
            /** Calibrated At */
            calibrated_at: string;
        };
        /** ThresholdOut */
        app__api__subjects__ThresholdOut: {
            /** Mu */
            mu: number;
            /** Sigma */
            sigma: number;
            /** Epsilon */
            epsilon: number;
            /** Z Multiplier */
            z_multiplier: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header: {
                Authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_datasets_upload_get: {
        parameters: {
            query?: never;
            header: {
                Authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_csv_upload_post: {
        parameters: {
            query?: never;
            header: {
                Authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_csv_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_upload_upload_analyze_post: {
        parameters: {
            query?: never;
            header: {
                Authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_analyze_upload_upload_analyze_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    commit_upload_upload_commit_post: {
        parameters: {
            query?: never;
            header: {
                Authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommitIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    train_train__dataset_id__post: {
        parameters: {
            query?: never;
            header: {
                Authorization: string;
            };
            path: {
                dataset_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_models_train_models_get: {
        parameters: {
            query?: never;
            header: {
                Authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    predict_predict__model_id__post: {
        parameters: {
            query?: never;
            header: {
                Authorization: string;
            };
            path: {
                model_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_predict_predict__model_id__post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_labeled_batches_predict__model_id__batches_get: {
        parameters: {
            query?: never;
            header: {
                Authorization: string;
            };
            path: {
                model_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictBatchSummaryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_labeled_batch_predict__model_id__batches__batch_id__get: {
        parameters: {
            query?: never;
            header: {
                Authorization: string;
            };
            path: {
                model_id: number;
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictBatchDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_anomalies_anomalies_get: {
        parameters: {
            query?: {
                model_id?: number | null;
                subject_id?: number | null;
                label?: string | null;
                outcome?: string | null;
                limit?: number;
            };
            header: {
                Authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnomalyOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    label_anomaly_anomalies__event_id__patch: {
        parameters: {
            query?: never;
            header: {
                Authorization: string;
            };
            path: {
                event_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LabelIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnomalyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_threshold_settings_threshold__model_id__get: {
        parameters: {
            query?: never;
            header: {
                Authorization: string;
            };
            path: {
                model_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["app__api__settings__ThresholdOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_threshold_settings_threshold__model_id__patch: {
        parameters: {
            query?: never;
            header: {
                Authorization: string;
            };
            path: {
                model_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecalibrateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["app__api__settings__ThresholdOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_subjects_subjects_get: {
        parameters: {
            query?: never;
            header: {
                Authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_subject_subjects_post: {
        parameters: {
            query?: never;
            header: {
                Authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_subject_subjects__subject_id__get: {
        parameters: {
            query?: never;
            header: {
                Authorization: string;
            };
            path: {
                subject_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_subject_subjects__subject_id__delete: {
        parameters: {
            query?: never;
            header: {
                Authorization: string;
            };
            path: {
                subject_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_subject_subjects__subject_id__patch: {
        parameters: {
            query?: never;
            header: {
                Authorization: string;
            };
            path: {
                subject_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubjectUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retrain_subject_subjects__subject_id__retrain_post: {
        parameters: {
            query?: {
                force?: boolean;
            };
            header: {
                Authorization: string;
            };
            path: {
                subject_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetrainOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_threshold_history_subjects__subject_id__threshold_history_get: {
        parameters: {
            query?: never;
            header: {
                Authorization: string;
            };
            path: {
                subject_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThresholdHistoryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    precheck_data_review_subjects__subject_id__data_review_precheck_post: {
        parameters: {
            query?: never;
            header: {
                Authorization: string;
            };
            path: {
                subject_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataReviewCandidateOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_data_review_candidates_subjects__subject_id__data_review_candidates_get: {
        parameters: {
            query?: never;
            header: {
                Authorization: string;
            };
            path: {
                subject_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataReviewCandidateOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    label_data_review_candidate_subjects__subject_id__data_review_candidates__candidate_id__patch: {
        parameters: {
            query?: never;
            header: {
                Authorization: string;
            };
            path: {
                subject_id: number;
                candidate_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DataReviewLabelIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataReviewCandidateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    train_alternative_subjects__subject_id__train_alternative_post: {
        parameters: {
            query?: never;
            header: {
                Authorization: string;
            };
            path: {
                subject_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrainAlternativeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainAlternativeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activate_model_subjects__subject_id__models__model_id__activate_post: {
        parameters: {
            query?: never;
            header: {
                Authorization: string;
            };
            path: {
                subject_id: number;
                model_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    personalization_experiments_personalization_post: {
        parameters: {
            query?: never;
            header: {
                Authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonalizationIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preset_demo_experiments_preset_demo_post: {
        parameters: {
            query?: never;
            header: {
                Authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresetDemoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evaluation_summary_experiments_evaluation_summary_get: {
        parameters: {
            query?: never;
            header: {
                Authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationSummaryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
