"""add missing FK indexes

Revision ID: 6fa0fc2c862a
Revises: d3041b96f6b0
Create Date: 2026-08-04 17:17:50.250716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fa0fc2c862a'
down_revision: Union[str, None] = 'd3041b96f6b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_notifications_event_id'), 'notifications', ['event_id'], unique=False)
    op.create_index(op.f('ix_upload_logs_dataset_id'), 'upload_logs', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_upload_logs_user_id'), 'upload_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_upload_logs_user_id'), table_name='upload_logs')
    op.drop_index(op.f('ix_upload_logs_dataset_id'), table_name='upload_logs')
    op.drop_index(op.f('ix_notifications_event_id'), table_name='notifications')
    # ### end Alembic commands ###
